---
- hosts: localhost
  connection: local
  tasks: 
  - name: VMWARE_USER
    debug: var=VMWARE_USER

  - name: Display all variables/facts known for a host
    debug: var=hostvars['localhost']

  - name: Create vCloud vApp
    vca_vapp:
      vapp_name: towerapp
      vm_name: towervm
      vm_cpus: 1
      vm_memory: 512
      state: deploy
      template_name: 'Template-CentOS6.8-x64'
      catalog_name: 'Public catalog'
      service_type: vcd
      vdc_name: 'OvDC-AteaStockholm6'
      org: "{{ org }}"
      username: "{{ VMWARE_USER }}"
      password: "{{ VMWARE_PASSWORD }}"
      host: "https://{{ VMWARE_HOST }}"
      api_version: '5.6'
    register: myvm

  - debug: var=myvm
