---
- hosts: localhost
  connection: local
  tasks: 
  - name: Create vCloud vApp
    vca_vapp:
      vapp_name: tower
      state: present
      template_name: Template-CentOS6.8-x64
      service_type: vcd
      vdc_name: OvDC-AOS01
      org: AteaStockholm6
      username: '{{ VMWARE_USER }}'
      password: '{{ VMWARE_PASSWORD }}'
      host: '{{ VMWARE_HOST }}'
