---
- hosts: localhost
  connection: local
  tasks: 
  - name: Create vCloud vApp
    vca_vapp:
      vapp_name: towerapp
      vm_name: towervm
      vm_cpus: 1
      vm_memory: 512
      state: deployed
      template_name: 'Template-CentOS6.8-x64'
      catalog_name: AOS-global01
      service_type: vcd
      vdc_name: 'OvDC-AteaStockholm6'
      org: "{{ org }}"
      username: "{{ VMWARE_USER }}"
      password: "{{ VMWARE_PASSWORD }}"
      host: "https://{{ VMWARE_HOST }}"
      api_version: '5.6'
