---
- hosts: localhost
  connection: local
  tasks: 
  - name: VMWARE_USER
    debug: var=VMWARE_USER
  - name: Display all variables/facts known for a host
    debug: var=hostvars['localhost']
  - name: Create vCloud vApp
    vca_vapp:
      vapp_name: tower
      state: present
      template_name: Template-CentOS6.8-x64
      catalog_name: AOS-global01
      service_type: vcd
      api_version: '5.5'
      vdc_name: OvDC-AOS01
      org: AteaStockholm6
      username: '{{ VMWARE_USER }}@AteaStockholm6'
      password: '{{ VMWARE_PASSWORD }}'
      host: 'manage2.myatea.net'
