---
- name: Create VM
  hosts: all
  tasks: 
  - # Deploy a guest from a template
- vsphere_guest:
    guest: newvm001
    from_template: yes
    template_src: win2012R2-template
    cluster: IntelCluster
    resource_pool: "/Resources"
    vm_extra_config:
      folder: ansible
      
