---
- hosts: localhost
  connection: local
  tasks: 
  - name: Create VMware VM
    vsphere_guest:
      guest: "{{vm_name}}"
      from_template: yes
      template_src: win2012R2-template
      cluster: INTELcluster
      resource_pool: "/Resources"
      vm_extra_config:
        folder: ansible
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: This is a test VM
        
  - name: Reconfigure VMware VM
    vsphere_guest:
      guest: "{{vm_name}}"
      state: reconfigured
      vm_hardware:
        memory_mb: "{{vm_memory}}"
        num_cpus: "{{vm_cpus}}"
        osid: centos64Guest
        scsi: paravirtual
