---
- name: Create VMware VM
  vsphere_guest:
    guest: "{{vm_name}}"
    from_template: yes
    template_src: RHEL7-template
    cluster: HC-CLUS
    resource_pool: "/Resources"
    vm_extra_config:
      folder: ansible
      vcpu.hotadd: yes
      mem.hotadd:  yes


- name: Reconfigure VMware VM
  vsphere_guest:
    guest: "{{vm_name}}"
    state: reconfigured
    force: true
    vm_extra_config:
      notes: This is a test VM
    vm_hardware:
      memory_mb: "{{vm_memory}}"
      num_cpus: "{{vm_cpus}}"
      osid: centos64Guest
      scsi: paravirtual

- name: show vmware_vm_facts
  vmware_vm_facts:
    username: "{{ lookup('env','VMWARE_USER')     }}"
    password: "{{ lookup('env','VMWARE_PASSWORD') }}"
    hostname: "{{ lookup('env','VMWARE_HOST')     }}"
  register: showVMs
- debug: var=showVMs

- name: get all vmware_vm_facts
  vmware_vm_facts:
    username: "{{ lookup('env','VMWARE_USER')     }}"
    password: "{{ lookup('env','VMWARE_PASSWORD') }}"
    hostname: "{{ lookup('env','VMWARE_HOST')     }}"
  register: VMs
  until: VMs.virtual_machines.{{vm_name}} is defined and VMs.virtual_machines.{{vm_name}}.ip_address
  retries: 10
  delay: 30
- debug: var=VMs

- name: Register Host in Ansible Inventory
  add_host:
    name: "{{vm_name}}"
    groups: vmware_vm
    ansible_ssh_host: "{{ item.ip_address }}"
  with_items:
  - "{{ VMs.virtual_machines[vm_name] }}"
