---
- name: Create VMware VM
  vsphere_guest:
    guest: "{{vm_name}}"
    from_template: yes
    template_src: rhel7-template
    cluster: INTELcluster
    resource_pool: "/Resources"
    vm_extra_config:
      folder: ansible
      vcpu.hotadd: yes
      mem.hotadd:  yes


- name: Reconfigure VMware VM
  vsphere_guest:
    guest: "{{vm_name}}"
    state: reconfigured
    force: true
    vm_extra_config:
      notes: This is a test VM
    vm_hardware:
      memory_mb: "{{vm_memory}}"
      num_cpus: "{{vm_cpus}}"
      osid: centos64Guest
      scsi: paravirtual

- name: show vmware_vm_facts
  vmware_vm_facts:
  register: showVMs
- debug: var=showVMs

- name: get all vmware_vm_facts
  vmware_vm_facts:
  register: VMs
  until: "'{{vm_name}}' in {{VMs.virtual_machines}}"
  retries: 10
  delay: 30

- name: Register Host in Ansible Inventory
  add_host: 
    name: "{{vm_name}}"
    groups: vmware_vm
    ansible_ssh_host: "{{ VMs.virtual_machines.{{vm_name}}.ip_address }}"
