---
- name: Create VMware VM
  vsphere_guest:
    guest: "{{vm_name}}"
    from_template: yes
    template_src: win2012R2-template
    cluster: INTELcluster
    resource_pool: "/Resources"
    vm_extra_config:
      folder: ansible
      vcpu.hotadd: yes
      mem.hotadd:  yes


- name: Reconfigure VMware VM
  vsphere_guest:
    guest: "{{vm_name}}"
    state: reconfigured
    force: true
    vm_extra_config:
      notes: This is a test VM
    vm_hardware:
      memory_mb: "{{vm_memory}}"
      num_cpus: "{{vm_cpus}}"
      osid: centos64Guest
      scsi: paravirtual
